config/routes.rb
FeedbackOverflow::Application.routes.draw do
  root to: 'topics#index'

  resources :topics

  resources :users
  get '/users/:id/topics' => 'users#user_topics', :as => 'user_topics'
  get '/users/:id/comments' => 'users#user_comments', :as => 'user_comments'

  resources :sessions, only: [:create]
  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#delete'

  resources :comments, only: [:create, :destroy, :edit, :update]


  post '/upvote/new' => 'upvotes#create', :as => 'upvote'

  get '/socratesoauth' => 'oauth#login', :as => 'oauth'
  get '/callback' => 'oauth#callback', :as => 'callback'


  resources :cohorts

  resources :scores, only: [:new, :create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :topic_id
  belongs_to :topic
  belongs_to :user

  validates :content, :presence => true

  def created_by?(user)
    self.user == user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate!, :only => [:create, :edit, :destroy]
  before_filter :load_and_authorize_comment, :only => [:edit, :destroy, :update]

	def create
		comment = current_user.comments.create(params[:comment])
		topic = comment.topic
    redirect_to topic_path(topic.slug)
	end

  def edit
    @topic = @comment.topic
  end

  def update
    @comment.update_attributes(params[:comment])
    if @comment.save
      redirect_to topic_path(@comment.topic)
    else
      render :edit
    end
  end

  def destroy
    topic = @comment.topic
    @comment.destroy
    redirect_to :back
  end

  private
    def load_and_authorize_comment
      @comment = Comment.find(params[:id])
    end
end

app/views/comments/_comment.html.erb
<%= form_for @comment do |f| %>
  <%= f.text_area :content %><br><br>
  <%= f.hidden_field :topic_id, value: @topic.id %>
  <%= f.submit("Clear Form", { :class => "button", :type => "reset" }) %>
	<%= f.submit("Submit", { :class => "button", :type => "submit" }) %>
<% end %>

app/views/comments/_comment_links.html.erb
<%  if comment.created_by?(current_user) %>
  (<%= link_to 'edit', edit_comment_path(comment)%> &#124; <%= link_to 'delete', comment_path(comment), :method => 'delete'  %>) <br>
<% end %>

app/views/comments/_comment_list.html.erb
<% comments.each do |comment| %>
  <p><%= comment.content %> &mdash; <%= link_to comment.user.name, user_path(comment.user) %>
  <%= render :partial=> 'comments/comment_links', :locals => {:comment => comment}%></p>
  <hr class="separator">
<% end %>

app/views/comments/edit.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1>EDIT COMMENT</h1>

		<%= render 'comment' %>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
		<%= render 'score' %>
	</div>
</div>