config/routes.rb
FeedbackOverflow::Application.routes.draw do
  root to: 'topics#index'

  resources :topics

  resources :users
  get '/users/:id/topics' => 'users#user_topics', :as => 'user_topics'
  get '/users/:id/comments' => 'users#user_comments', :as => 'user_comments'

  resources :sessions, only: [:create]
  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#delete'

  resources :comments, only: [:create, :destroy, :edit, :update]


  post '/upvote/new' => 'upvotes#create', :as => 'upvote'

  get '/socratesoauth' => 'oauth#login', :as => 'oauth'
  get '/callback' => 'oauth#callback', :as => 'callback'


  resources :cohorts

  resources :scores, only: [:new, :create]

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :content, :anonymous

  belongs_to :user
  has_many :comments
  has_many :upvotes
  has_many :users, :through => :upvotes

  has_many :scores


  validates :title, :content, :presence => true
  validates :title, uniqueness: true
  before_create :to_slug

  def to_param
    slug
  end

  def created_by?(user)
    self.user == user
  end

  # def self.sorted_by_upvotes
  #   self.all.sort {|topic1, topic2| topic2.upvotes.count <=> topic1.upvotes.count }
  # end

  def upvoters
    self.users
  end

  def avg_a
    actionable_total = self.scores.inject(0){|sum, score| sum + score.actionable unless score.actionable.nil?}
    (actionable_total.to_f/self.scores.count).round(2)
  end

  def avg_s
    specific_total = self.scores.inject(0){|sum, score| sum + score.specific unless score.actionable.nil?}
    (specific_total.to_f/self.scores.count).round(2)
  end

  def avg_k
    kind_total = self.scores.inject(0){|sum, score| sum + score.kind unless score.actionable.nil?}
    (kind_total.to_f/self.scores.count).round(2)
  end



  private
    def to_slug
      self.slug = self.title.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-')
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :load_and_authorize_topic, :only => [:edit, :update, :destroy]

  def index
    @topics = Topic.find(:all, :order => 'upvotes_count DESC')
    @recent_topic = Topic.last
  end

  def new
    @topic = Topic.new
  end

  def show
    @topic = Topic.find_by_slug(params[:id])
    @comment = Comment.new
    @score = Score.where(user_id: current_user.id, topic_id: @topic.id).first_or_initialize if signed_in?# IF user hasn't left Score yet otherwise show graph
    @graph = LazyHighCharts::HighChart.new('column') do |f|
      f.series( :name=>'Scores',:data=> [@topic.avg_s, @topic.avg_a, @topic.avg_k], :shadow => true, :borderWidth => 0, :color => "#0e9896")
      f.options[:chart][:defaultSeriesType] = "column"
      f.options[:chart][:backgroundColor] = "#ecf0f1"
      f.xAxis(categories: ['Specific', 'Actionable', 'Kind'])
      f.yAxis(min: 1, max: 5, title: nil, labels: false, gridLineWidth: 0)
      f.legend(enabled: false)
      f.options[:series]
    end
  end

 def edit
 end

 def create
  @topic = current_user.topics.build(params[:topic])
  if @topic.save
    redirect_to topic_path(@topic)
  else
    render :new
  end
end

def update
  @topic.update_attributes(params[:topic])
  if @topic.save
    flash[:success] = "Topic has been successfully updated!"
    redirect_to topic_path
  else
    render :edit
  end
end

  def destroy
    p '*' * 1000
    @topic.comments.destroy_all
    @topic.scores.destroy_all
    @topic.destroy
    redirect_to root_url
  end

  private
    def load_and_authorize_topic
      @topic = Topic.find_by_slug(params[:id])
      redirect_to root_path unless @topic.created_by?(current_user)
    end

end

app/views/topics/_chart.html.erb
  <%= high_chart("chart", graph) do |c| %>
  <%= raw "options.tooltip.formatter = function() {return this.x+': ' + this.y}" %>
  <% end %>

app/views/topics/_list_topics.html.erb
<ul id="topics">
  <% topics.each do |topic| %>
    <li>
      <span class="upvote <%= add_style_to_upvoted(topic) %>">
      <%= link_to '^', upvote_path(topic), method: 'post', remote: true %>
      </span>

      <span class='upvote_count'><%= topic.upvotes_count %></span>
      &mdash; <%= link_to truncate(topic.title), topic_path(topic) %>
      <span class='author'><em>by <%= topic.anonymous? ? "Anonymous" : link_to(topic.user.name, user_path(topic.user))%></em></span><%= time_ago_in_words(topic.created_at) %> ago </li>
  <% end %>
</ul>

app/views/topics/_recent.html.erb
<h3>MOST RECENT TOPIC</h3>

<% if recent %>
  <span class="upvote <%= add_style_to_upvoted(recent) %>">
	<%= link_to '^', upvote_path(recent), method: 'post', remote: true %></span>
  <span class='upvote_count'><%= recent.upvotes_count %></span>
  <span id="recent"><%= link_to recent.title, topic_path(recent) %></span><br>


  <span id="author"><%= time_ago_in_words(recent.created_at) %> ago &mdash; <%= recent.anonymous? ? "Anonymous" : link_to(recent.user.name, user_path(recent.user))%></span><br>
<% end %>

app/views/topics/_score.html.erb
<div class="metafeedback">
  
  <h2>METAFEEDBACK</h2>

  <div id="score">
    <% if signed_in? %>
      <% if current_user.has_scored?(@topic) %>
        <div id="existing_score">
          <%= render partial: "scores/completed", locals: {score: @score} %>
        </div>
      <% else %>

    <div id="create_score">
      <h3>ADD SCORE</h3>
      <%= form_for @score, :remote => true, :data => {topic_id: @topic.id} do |f| %>
      <%= f.hidden_field :topic_id, :value => @topic.id %>
      This feedback is specific: <br><%= f.select :specific, options_for_select([['---', nil], ['Strongly Disagree', '1'], ['Disagree', '2'], ['Neutral', '3'], ['Agree', '4'], ['Strongly Agree', '5']]) %><br>
      This feedback is actionable: <br><%= f.select :actionable, options_for_select([['---', nil], ['Strongly Disagree', '1'], ['Disagree', '2'], ['Neutral', '3'], ['Agree', '4'], ['Strongly Agree', '5']]) %><br>

      This feedback is kind: <br><%= f.select :kind, options_for_select([['---', nil], ['Strongly Disagree', '1'], ['Disagree', '2'], ['Neutral', '3'], ['Agree', '4'], ['Strongly Agree', '5']]) %><br>
      <%= f.submit "Submit" %>
      <% end %>
    </div>
    <% end %>
  </div>
  <% end %>

  <h3>STATISTICS</h3>
  
  <div id='stats'>
    <%= render partial: "chart", locals: {graph: @graph} %>
  </div>
</div>

app/views/topics/edit.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1><%= @topic.title %></h1>

		<%= form_for @topic do |f| %>
			<%= f.label :title %><br>
			<%= f.text_field :title %><br><br>
			<%= f.label :content %><br>
			<%= f.text_area :content %><br><br>
			<%= f.submit("Clear Form", { :class => "button", :type => "reset" }) %>
			<%= f.submit("Submit", { :class => "button", :type => "submit" }) %>
		<% end %>

		<%= link_to 'delete', topic_path, :method => 'delete' %>
	</div>
</div>

app/views/topics/index.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1>ALL TOPICS</h1>
		<%= render :partial => 'list_topics', :locals => {:topics => @topics} %>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
    <%= render partial: 'recent', locals: {recent: @recent_topic} %>
	</div>
</div>

app/views/topics/new.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1>CREATE TOPIC</h1>

		<%= form_for @topic do |f| %>
			<%= f.label :title, "Title" %><br>
			<%= f.text_field :title %><br><br>

			<%= f.label :content, "Comment" %><br>
			<%= f.text_area :content %><br><br>

		  <!-- still need to fix alignment problem with checkbox and label - ryan -->
			<%= f.label :anonymous, "Post anonymously?" %> <%= f.check_box :anonymous %><br><br>

			<%= f.submit("Clear Form", { :class => "button", :type => "reset" }) %>
			<%= f.submit("Submit", { :class => "button", :type => "submit" }) %>
		<% end %>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
		<h3>LEAVING GOOD FEEDBACK</h3>
		<p>Make sure your feedback is...</p>
		<dl>
			<dt><strong>Specific</strong></dt>
			<dd>
				Avoid vague or general feedback. Don't make people read between the lines to figure out what you mean.
			</dd>
			<dt><strong>Actionable</strong></dt>
			<dd>
				Someone should be able to act on your feedback. If someone can't do anything to address your feedback, then your feedback might actually be whining or gossip, so be careful of that.
			</dd>
			<dt><strong>Kind</strong></dt>
			<dd>
				<quote><em>"There's only one rule that I know of, babies &mdash; God damn it, you've got to be kind."</em></quote>
			</dd>
	</div>
</div>

app/views/topics/show.html.erb
 <div id="content_left">
  <div id="content_left_inner">
    <h1><%= @topic.title %></h1>
    
    <span class="upvote <%= add_style_to_upvoted(@topic) %>">
    <%= link_to '^', upvote_path(@topic), method: 'post', remote: true %>
    </span>

    <span class='upvote_count'><%= @topic.upvotes_count %></span>

    <%= link_to 'Edit', edit_topic_path(@topic) if @topic.created_by?(current_user) %>

    <p><%= @topic.content %></p>


    <h3>Comments</h3>
    <%= render :partial => 'comments/comment_list', :locals => {:comments => @topic.comments} %>

    <strong>Add Comment</strong>
    <%= render 'comments/comment' %>
  </div>
</div>


<div id="content_right" >
  <div id="content_right_inner">
    <%= render 'score' %>
  </div>
</div>