config/routes.rb
FeedbackOverflow::Application.routes.draw do
  root to: 'topics#index'

  resources :topics

  resources :users
  get '/users/:id/topics' => 'users#user_topics', :as => 'user_topics'
  get '/users/:id/comments' => 'users#user_comments', :as => 'user_comments'

  resources :sessions, only: [:create]
  get '/signup' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#delete'

  resources :comments, only: [:create, :destroy, :edit, :update]


  post '/upvote/new' => 'upvotes#create', :as => 'upvote'

  get '/socratesoauth' => 'oauth#login', :as => 'oauth'
  get '/callback' => 'oauth#callback', :as => 'callback'


  resources :cohorts

  resources :scores, only: [:new, :create]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :cohort_id, :socrates_auth
  has_secure_password
  has_many :topics
  has_many :upvotes
  has_many :upvoted_topics, through: :upvotes,  source: :topic
  has_many :scored_topics, through: :scores, source: :topic
  has_many :scores
  has_many :comments
  belongs_to :cohort


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true,
                       uniqueness: true

  validates :email, presence: true,
                    uniqueness: true,
                    format: {with: VALID_EMAIL_REGEX}

  validates :name_slug, uniqueness: true

  before_save {self.email = email.downcase}
  before_create :create_remember_token, :titalize_name


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def authorize_user(current_user)
    self == current_user
  end

  def has_scored?(topic)
    scored_topics.include?(topic)
  end

  def to_param
    name_slug
  end

  #ADD UPDATED COMMENTS ASWELL
  def influence
    self.topics.map(&:upvotes_count).inject(:+)
  end

  def topic_stats
    self.topics.reject(&:anonymous).count
  end

  # GET RID OF ANONYMOUS COMMENTS ASWELL
  def comment_stats
    self.comments.count
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

    def titalize_name
      self.name_slug = self.name.downcase.gsub(/[^a-z1-9]+/, '-').chomp('-')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_and_authorize_user, :only => [:edit, :update]
  before_filter :load_user_by_slug, :only => [:show, :user_topics, :user_comments]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Sucessfully created a new account"
      sign_in @user
      redirect_to root_url
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by_name_slug(params[:id])
    @topics = @user.topics.order('upvotes_count DESC LIMIT 10')
  end

  def edit
  end

  def update
    @user.update_attributes(params[:user])
    if @user.save
      flash[:success] = "User successfully updated"
      redirect_to root_url
    else
      @errors = @user.errors.full_messages
      render :edit
    end
  end

  def user_topics
  end

  def user_comments
  end

private
  def load_user_by_slug
    @user = User.find_by_name_slug(params[:id])
  end
end

app/views/users/_errors.html.erb
<% if @errors %>
  <% @errors.each do |error| %>
    <p class="error"><%= error %></p>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'errors' %>

<%= form_for @user do |f| %>
  <%= f.label :name, "Name" %><br>
  <%= f.text_field :name %><br><br>
  <%= f.label :email, "E-mail" %><br>
  <%= f.text_field :email %><br><br>

  <% if !@user.socrates_auth? %>
    <%= f.label :password, "Password" %><br>
    <%= f.password_field :password %><br><br>
    <%= f.label :password_confirmation, "Password Confirmation" %><br>
    <%= f.password_field :password_confirmation %><br><br>
  <% end %>
  
  <%= f.submit("Clear Form", { :class => 'button', :type => "reset" }) %>
  <%= f.submit("Submit", { :class => 'button', :type => "submit" }) %>
<% end %>

app/views/users/edit.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1>EDIT PROFILE</h1>

		<%= render 'form' %>

		<%= link_to 'cancel', user_path %>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
		<h3>LEAVING GOOD FEEDBACK</h3>
		<p>Make sure your feedback is...</p>
		<dl>
			<dt><strong>Specific</strong></dt>
			<dd>
				Avoid vague or general feedback. Don't make people read between the lines to figure out what you mean.
			</dd>
			<dt><strong>Actionable</strong></dt>
			<dd>
				Someone should be able to act on your feedback. If someone can't do anything to address your feedback, then your feedback might actually be whining or gossip, so be careful of that.
			</dd>
			<dt><strong>Kind</strong></dt>
			<dd>
				<quote><em>"There's only one rule that I know of, babies &mdash; God damn it, you've got to be kind."</em></quote>
			</dd>
	</div>
</div>

app/views/users/new.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1>SIGN UP</h1>
		<p>Please fill out the form below to create a new account. All fields required.</p>
		<%= render 'form' %>
		<p><%= link_to 'back', root_path %></p>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
		<h3>LEAVING GOOD FEEDBACK</h3>
		<p>Make sure your feedback is...</p>
		<dl>
			<dt><strong>Specific</strong></dt>
			<dd>
				Avoid vague or general feedback. Don't make people read between the lines to figure out what you mean.
			</dd>
			<dt><strong>Actionable</strong></dt>
			<dd>
				Someone should be able to act on your feedback. If someone can't do anything to address your feedback, then your feedback might actually be whining or gossip, so be careful of that.
			</dd>
			<dt><strong>Kind</strong></dt>
			<dd>
				<quote><em>"There's only one rule that I know of, babies &mdash; God damn it, you've got to be kind."</em></quote>
			</dd>
	</div>
</div>

app/views/users/show.html.erb
<div id="profile_wrapper">

 <!-- INFORMATION SECTION -->
 <section class='information_section'>
  <div class="info_box">

    <div class="avatar_container">
      <%= image_tag avatar_url(@user), :alt => 'avatar', :id => 'avatar' %>
    </div> <!-- end div avatar_cotnainer -->

    <div class="user_info">
     <p><strong>Name:</strong> <%= @user.name %></p>
     <% if @user.socrates_auth? %>
     <p><strong>Cohort:</strong> <%= @user.cohort.name %></p>
     <p><strong>Status:</strong> <%= @user.cohort.status %></p>
     <p><strong>Location:</strong> <%= @user.cohort.location %></p>
     <% end %>
   </div> <!-- end user_info -->

   <div class="influence_box">
     <p><%= @user.upvotes.empty? ? "0" : @user.influence %></p>
     <p>Influence</p>
   </div> <!-- end influence_score -->




   <div id="stats_box">


    <div class="topics_stats">
      <p><%= @user.topic_stats %></p>
      <strong><%= link_to determine_plural(@user.topic_stats, 'Topic'), user_topics_path %></strong>
    </div> <!-- end topics_stats -->

    <div class="comments_stats">
      <p><%= @user.comment_stats %></p>
      <strong><%= link_to determine_plural(@user.comment_stats, 'Comment'), user_comments_path %></strong>
    </div> <!-- end comments_stats -->


  </div><!-- end stats_box -->

  <div class="edit_profile">
    <%= link_to 'Edit Profile', edit_user_path(@user) if @user.authorize_user(current_user) %>
  </div> <!-- end edit_profile -->



</div> <!-- end info_box -->
</section> <!-- end information_section -->


<!-- USER TOPIC SECTION -->
<section id="user_topics_section">
  <div class="topics_box">
  <% if @user.topics.empty? %>
  <h3><%= @user.name.upcase %> HAS NO TOPICS YET</h3>
  <% else %>
    <h2><%= @user.name.upcase %>'S MOST INFLUENTIAL TOPICS</h2>
    <div class="topics_list">
      <%= render :partial => 'topics/list_topics', :locals => {:topics => non_anonymous_topics(@topics)} %>
    </div>
  <% end %><!-- end topics_list -->
  </div> <!-- end topics_box -->

</section> <!-- end user_topics section -->

</div>

app/views/users/user_comments.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1><%= @user.name.upcase %>'S COMMENTS</h1>

		<%= render :partial => 'comments/comment_list', :locals => {:comments => @user.comments} %>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
		<h3>LEAVING GOOD FEEDBACK</h3>
		<p>Make sure your feedback is...</p>
		<dl>
			<dt><strong>Specific</strong></dt>
			<dd>
				Avoid vague or general feedback. Don't make people read between the lines to figure out what you mean.
			</dd>
			<dt><strong>Actionable</strong></dt>
			<dd>
				Someone should be able to act on your feedback. If someone can't do anything to address your feedback, then your feedback might actually be whining or gossip, so be careful of that.
			</dd>
			<dt><strong>Kind</strong></dt>
			<dd>
				<quote><em>"There's only one rule that I know of, babies &mdash; God damn it, you've got to be kind."</em></quote>
			</dd>
	</div>
</div>

app/views/users/user_topics.html.erb
<div id="content_left">
	<div id="content_left_inner">
		<h1><%= @user.name.upcase %>'S TOPICS</h1>

		<%= render :partial => 'topics/list_topics', :locals => {:topics => non_anonymous_topics(@user.topics)} %>
	</div>
</div>

<div id="content_right">
	<div id="content_right_inner">
		<h3>LEAVING GOOD FEEDBACK</h3>
		<p>Make sure your feedback is...</p>
		<dl>
			<dt><strong>Specific</strong></dt>
			<dd>
				Avoid vague or general feedback. Don't make people read between the lines to figure out what you mean.
			</dd>
			<dt><strong>Actionable</strong></dt>
			<dd>
				Someone should be able to act on your feedback. If someone can't do anything to address your feedback, then your feedback might actually be whining or gossip, so be careful of that.
			</dd>
			<dt><strong>Kind</strong></dt>
			<dd>
				<quote><em>"There's only one rule that I know of, babies &mdash; God damn it, you've got to be kind."</em></quote>
			</dd>
	</div>
</div>